name:                Tetris
version:             0.1.0.0
github:              "ptolemycasio/Tetris"
license:             BSD3
author:              "Casio Fujii"
maintainer:          "you.likelihood@gmail.com"
copyright:           "2019 Casio Fujii"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ptolemycasio/Tetris#readme>

dependencies:
- base >= 4.7 && < 5
- GLUT
- random
- time

library:
  source-dirs: src

executables:
  tetris:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tetris

tests:
  Tetris-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tetris
